# Taken from: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-the-maven-central-repository
# Also: https://gist.github.com/sualeh/ae78dc16123899d7942bc38baba5203c
name: Publish Maven Central
on:
  release:
    types: [ 'published' ]

env:
  JAVA_VERSION: '17'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_BUILD_TOOL: 'maven'

jobs:
  test:
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
        # Skip firefox on windows, as firefox currently does not work on it: https://github.com/browser-actions/setup-firefox/issues/252
        if: matrix.os != 'windows-latest'
      - uses: browser-actions/setup-edge@v1
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.JAVA_BUILD_TOOL }}
      - name: Run tests on Windows
        if: matrix.os == 'windows-latest'
        shell: cmd
        # Remember to use circumflexes for newline escaping, we're in a cmd environment.
        # See above reasoning for firefox exclusion.
        run: |
          mvn clean test --no-transfer-progress ^
          -Dxray.authentication.xray.clientId=${{ secrets.XRAY_CLIENT_ID }} ^
          -Dxray.authentication.xray.clientSecret=${{ secrets.XRAY_CLIENT_SECRET }} ^
          -DexcludedGroups=firefox
      - name: Run tests on Linux
        if: matrix.os == 'ubuntu-latest'
        # Remember to use backslashes for newline escaping, we're in a bash environment.
        # Exclude Internet Explorer, as it does not run on Linux: https://www.selenium.dev/documentation/ie_driver_server/
        run: |
          export DISPLAY=:99
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
          mvn clean test --no-transfer-progress \
          -Dxray.authentication.xray.clientId=${{ secrets.XRAY_CLIENT_ID }} \
          -Dxray.authentication.xray.clientSecret=${{ secrets.XRAY_CLIENT_SECRET }} \
          -DexcludedGroups=ie

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          cache: ${{ env.JAVA_BUILD_TOOL }}
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Install gpg secret key
        run: cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
      - name: Publish package
        # Skip tests during deployment, we have tested everything already.
        run: |
          mvn --batch-mode \
          -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          -DskipTests \
          clean deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
