# Run tests on different browser and build the QTAF sources with the different Java versions, to check if our software works.
name: Run tests on different browser and check Java compatibility

on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
env:
  JAVA_DISTRIBUTION: 'zulu'

jobs:
  execute_on_different_browser:
    runs-on: ubuntu-latest
    timeout-minutes: 15 
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
        include:
          - browser: chrome
            port: 4444
          - browser: firefox
            port: 4445
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - name: Execute QTAF test
        run: mvn clean test -q -Ddriver.name=${{matrix.browser}}-remote -Ddriver.remoteUrl=http://127.0.0.1:${{matrix.port}}/wd/hub

  build_on_different_java_versions:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        JAVA_VERSION: ['17', '18', '19']
    steps:
      - uses: ./.github/workflows/Test.yml
        with:
          java-version: ${{ matrix.JAVA_VERSION }}
          java-distribution: ${{ env.JAVA_DISTRIBUTION }}
            
