name: Run QTAF Unit Tests
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      java-distribution:
        required: false
        type: string
        default: "zulu"

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: qytera-gmbh/actions-check-secrets@v1
        with:
          names: |
            XRAY_CLIENT_ID
            XRAY_CLIENT_SECRET
            SONAR_TOKEN
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  test:
    needs: [check-secrets]
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        include:
          - os: "windows-latest"
            command: |
              mvn --batch-mode --no-transfer-progress clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar `
              "-Dsonar.host.url=https://sonarcloud.io" `
              "-Dsonar.organization=qytera-gmbh" `
              "-Dsonar.projectKey=Qytera-Gmbh_QTAF" `
              "-Dsonar.login=$Env:SONAR_TOKEN" `
              "-Dsonar.pullrequest.key=${{github.event.pull_request.number}}" `
              "-Dsonar.pullrequest.branch=${{github.head_ref}}" `
              "-Dsonar.pullrequest.base=${{github.base_ref}}" `
              "-Dxray.authentication.xray.clientId=$Env:XRAY_CLIENT_ID" `
              "-Dxray.authentication.xray.clientSecret=$Env:XRAY_CLIENT_SECRET"
          - os: "ubuntu-latest"
            # Exclude Internet Explorer, as it does not run on Linux: https://www.selenium.dev/documentation/ie_driver_server/
            # Also: https://stackoverflow.com/questions/63125480/running-a-gui-application-on-a-ci-service-without-x11
            command: |
              export DISPLAY=:99
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
              mvn --batch-mode --no-transfer-progress clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.organization=qytera-gmbh \
              -Dsonar.projectKey=Qytera-Gmbh_QTAF \
              -Dsonar.login=$SONAR_TOKEN \
              -Dsonar.pullrequest.key=${{github.event.pull_request.number}} \
              -Dsonar.pullrequest.branch=${{github.head_ref}} \
              -Dsonar.pullrequest.base=${{github.base_ref}} \
              -Dxray.authentication.xray.clientId=$XRAY_CLIENT_ID \
              -Dxray.authentication.xray.clientSecret=$XRAY_CLIENT_SECRET \
              -DexcludedGroups=ie,edge

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
      - uses: browser-actions/setup-edge@v1
        # Edge currently does not work.
        if: matrix.os != 'ubuntu-latest'
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: "maven"
      - name: Run tests
        run: ${{ matrix.command }}
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
