# Run tests on different browser and build the QTAF sources with the different Java versions, to check if our software works.
name: Run tests on different browser and check Java compatibility

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  execute_on_different_browser:
    runs-on: ubuntu-latest
    timeout-minutes: 15 
    strategy:
      matrix:
        browser: ['chrome', 'firefox']
        include:
          - browser: chrome
            port: 4444
          - browser: firefox
            port: 4445
    services:
      chrome:
        image: selenium/standalone-chrome
        ports:
          - 4444:4444
      firefox:
        image: selenium/standalone-firefox
        ports:
          - 4445:4444
    steps:
      - name: Execute QTAF test
        run: mvn clean test -q -Ddriver.name=${{matrix.browser}}-remote -Ddriver.remoteUrl=http://127.0.0.1:${{matrix.ports}}/wd/hub

  build_on_different_java_version:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        version: ['17', '18', '19']
    steps:
      - run: echo Tests runs for Java Version ${{matrix.version}}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      - name: Build docker image
        run: sh ./scripts/docker/build-java${{matrix.version}}-image.sh
