name: Run QTAF Unit Tests
on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: number
      java-distribution:
        required: false
        type: string
        default: "zulu"
    secrets:
      XRAY_CLIENT_ID:
        required: true
        description: "Xray Cloud API client ID"
      XRAY_CLIENT_SECRET:
        required: true
        description: "Xray Cloud API client secret"

jobs:
  test:
    strategy:
      matrix:
        os: ["windows-latest", "ubuntu-latest"]
        include:
          - os: "windows-latest"
            # Exclude Firefox, as it currently does not work on Windows: https://github.com/browser-actions/setup-firefox/issues/252
            command: |
              mvn --version
              mvn clean test --no-transfer-progress ^
              -Dxray.authentication.xray.clientId=%XRAY_CLIENT_ID% ^
              -Dxray.authentication.xray.clientSecret=%XRAY_CLIENT_SECRET% ^
              -DexcludedGroups=firefox
          - os: "ubuntu-latest"
            # Exclude Internet Explorer, as it does not run on Linux: https://www.selenium.dev/documentation/ie_driver_server/
            # Also: https://stackoverflow.com/questions/63125480/running-a-gui-application-on-a-ci-service-without-x11
            command: |
              which mvn
              which Xvfb
              export DISPLAY=:99
              sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
              mvn clean test --no-transfer-progress \
              -Dxray.authentication.xray.clientId=$XRAY_CLIENT_ID \
              -Dxray.authentication.xray.clientSecret=$XRAY_CLIENT_SECRET \
              -DexcludedGroups=ie
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: browser-actions/setup-chrome@v1
      - uses: browser-actions/setup-firefox@v1
        # See above reasoning for Firefox exclusion.
        if: matrix.os != 'windows-latest'
      - uses: browser-actions/setup-edge@v1
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: "maven"
      - name: Run tests
        shell: cmd
        run: ${{ matrix.command }}
        env:
          XRAY_CLIENT_ID: ${{ secrets.XRAY_CLIENT_ID }}
          XRAY_CLIENT_SECRET: ${{ secrets.XRAY_CLIENT_SECRET }}
